# Feature Scaling

In [1]:
import numpy as np

In [2]:
X = np.array([[1., -1., 2.],
             [2., 0., 0.],
             [0., 1., -1.]])

In [3]:
from sklearn import preprocessing

In [6]:
X_scaled = preprocessing.scale(X)
print(X_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [7]:
print(X_scaled.mean(axis=0))

[0. 0. 0.]


In [9]:
print(X_scaled.std(axis=0))

[1. 1. 1.]


In [13]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

print(scaler.transform(X))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [16]:
X_test = [[1, 1, 0]]
print(scaler.transform(X_test))

[[ 0.          1.22474487 -0.26726124]]
