## Numpy

In [10]:
list = [17, " ", [  ]]
list[2] = 81
print(list)

[17, ' ', 81]


In [16]:
import numpy as np

list = [1, 2, 3, 4]
list1 = np.array(list)
print(list1.dtype)
print(list1)

int32
[1 2 3 4]


In [24]:
# some helper functions
x = np.zeros(8)
print(x)
print(x.dtype)
x1 = np.zeros(8, int)
print(x1)
print(x1.dtype)

y = np.ones(7)
print(y)
print(y.dtype)
y1 = np.ones(7, str)
print(y1)
print(y1.dtype)


[0. 0. 0. 0. 0. 0. 0. 0.]
float64
[0 0 0 0 0 0 0 0]
int32
[1. 1. 1. 1. 1. 1. 1.]
float64
['1' '1' '1' '1' '1' '1' '1']
<U1


In [28]:
x1[1] = '3'
print(x1)
# x1[2] = "oops"

[0 3 0 0 0 0 0 0]


In [35]:
# creating multidimensional array
x2 = np.zeros((3, 4), int)
print(x2)
x3 = np.zeros((3, 4, 2), int)
print(x3)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [52]:
# Accessing Data
ran1 = np.random.randint(0, 25, (3, 2))
print(ran1)
ran2 = np.random.randint(25, 50, (2, 1, 4))
print(ran2)

print(ran1[0][1])
print(ran1[2][0])

print(ran2[1][0][2])

print(ran1[:, 0])
print(ran1[0:2, 1])
print(ran2[:, 0, 1:3])

print(ran1.shape)
print(ran2.shape)

[[17  2]
 [14 10]
 [24 22]]
[[[40 32 45 39]]

 [[33 41 41 27]]]
2
24
41
[17 14 24]
[ 2 10]
[[32 45]
 [41 41]]
(3, 2)
(2, 1, 4)


In [61]:
# numpy operations
o1 = np.array([1, 2, 3, 4, 5])
o2 = np.array([6, 7, 8, 9, 10])
print(o1 + 2)
print(o1 + o2)
print(o1 * 2)
print(o1 * o2)
print(o1 ** 2)
print(o1 ** o2)

print(o1.sum())
print(o1.mean())

[3 4 5 6 7]
[ 7  9 11 13 15]
[ 2  4  6  8 10]
[ 6 14 24 36 50]
[ 1  4  9 16 25]
[      1     128    6561  262144 9765625]
15
3.0
